### ISSUE TITLE
Worker IP created, even when no workers

### ISSUE THREAD

**Issue by solarisfire** [hcloud-talos/terraform-hcloud-talos#90] opened 2024-10-04 16:08 UTC
I have a cluster of 5 control plane nodes, which act as workers, with 0 dedicated workers.

In my config I have:

<pre>
control_plane_count       = 5
worker_count       = 0
</pre>

However, when run, a worker IPv4 address is created, and left unassigned.

![image](https://github.com/user-attachments/assets/03552d57-9f08-44e7-bbcf-aa8c51446832)

**Comment by mrclrchtr** [comment] 2024-10-04 18:19
Thank you very much. This is a duplicate of https://github.com/hcloud-talos/terraform-hcloud-talos/issues/70

I will look at this next week.

**Closed as completed by mrclrchtr** 2024-10-04 18:19 UTC
